version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: distribuida
    ports:
      - 5433:5432

  app-books:
    image: josued21/app-books:1.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-book.rule=Host(`app-book`)"
      - "traefik.http.routers.app-book.entrypoints=web"

    environment:
      - DB_URL: jdbc:postgresql://db:5432/distribuida
      - DB_USERNAME: postgres
      - DB_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003

  app-authors:
    image: josued21/app-authors:1.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-author.rule=Host(`app-author`)"
      - "traefik.http.routers.app-author.entrypoints=web"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/distribuida
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "9090:80"



  traefik:
    image: "traefik:v3.0"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9090" # entrypoint on docker e.g: 8888
    ports:
      - "9090:9090" # localhost : entrypoint on docker e.g:  4545:8888
      - "6099:8080"

#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#volumes:
#  slva: